spring:
  application:
    name: motorplus
  main :
    banner-mode: off
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/motorplus}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 465
    username: motorplussupport@gmail.com
    password: ddzohrswsaqwhoyb
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

app:
  frontend-url: http://localhost:5173

mybatis:
  type-handlers-package: com.motorplus.motorplus.mybatis
  default-scripting-language: org.apache.ibatis.scripting.xmltags.XMLLanguageDriver
  configuration:
    map-underscore-to-camel-case: true

